### ISSUE TITLE
rmsprop confused by the last update x

### ISSUE THREAD

**Issue by shanghai-Jerry** [ncchen55414/Spring-2016-CS231N#1]
I am confused that the next_x should be updated by next_x += (rmsprop update rule function) in the file cs231n/optim.py not x +=, right ?

**Comment by hofingermarkus** [comment]
I think it's just written in a confusing way.
`next_x = x `
...
`x += ...`
=> looks like x and next_x reference the same numpy array and therefore share same data since the x.copy() was not used...

https://github.com/ncchen55414/Winter-2016-CS231N/blob/d4cb5c7b71c5e34b2bf8909a97bf803e82bf5124/Assignment2/cs231n/optim.py#L104-L106
